import { Pokemon } from './common';

type TypeEffectivenessObject<T extends string> = {
  [key in T]: {
    [key2 in T]?: 0 | 0.5 | 2;
  }
};

// typeEffectivenessObject[Attack Type][Defense Type]
export const typeEffectivenessObject: TypeEffectivenessObject<Pokemon.Type> = {
  [Pokemon.Type.NORMAL]: {
    [Pokemon.Type.ROCK]: 0.5,
    [Pokemon.Type.GHOST]: 0,
    [Pokemon.Type.STEEL]: 0.5,
  },
  [Pokemon.Type.FIGHTING]: {
    [Pokemon.Type.NORMAL]: 2,
    [Pokemon.Type.FLYING]: 0.5,
    [Pokemon.Type.POISON]: 0.5,
    [Pokemon.Type.ROCK]: 2,
    [Pokemon.Type.BUG]: 0.5,
    [Pokemon.Type.GHOST]: 0,
    [Pokemon.Type.STEEL]: 2,
    [Pokemon.Type.PSYCHIC]: 0.5,
    [Pokemon.Type.ICE]: 2,
    [Pokemon.Type.DARK]: 2,
    [Pokemon.Type.FAIRY]: 0.5,
  },
  [Pokemon.Type.FLYING]: {
    [Pokemon.Type.FIGHTING]: 2,
    [Pokemon.Type.ROCK]: 0.5,
    [Pokemon.Type.BUG]: 2,
    [Pokemon.Type.STEEL]: 0.5,
    [Pokemon.Type.GRASS]: 2,
    [Pokemon.Type.ELECTRIC]: 0.5,
  },
  [Pokemon.Type.POISON]: {
    [Pokemon.Type.POISON]: 0.5,
    [Pokemon.Type.GROUND]: 0.5,
    [Pokemon.Type.ROCK]: 0.5,
    [Pokemon.Type.GHOST]: 0.5,
    [Pokemon.Type.STEEL]: 0,
    [Pokemon.Type.GRASS]: 2,
    [Pokemon.Type.FAIRY]: 2,
  },
  [Pokemon.Type.GROUND]: {
    [Pokemon.Type.FLYING]: 0,
    [Pokemon.Type.POISON]: 2,
    [Pokemon.Type.ROCK]: 2,
    [Pokemon.Type.BUG]: 0.5,
    [Pokemon.Type.STEEL]: 2,
    [Pokemon.Type.FIRE]: 2,
    [Pokemon.Type.GRASS]: 0.5,
    [Pokemon.Type.ELECTRIC]: 2,
  },
  [Pokemon.Type.ROCK]: {
    [Pokemon.Type.FIGHTING]: 0.5,
    [Pokemon.Type.FLYING]: 2,
    [Pokemon.Type.GROUND]: 0.5,
    [Pokemon.Type.BUG]: 2,
    [Pokemon.Type.STEEL]: 0.5,
    [Pokemon.Type.FIRE]: 2,
    [Pokemon.Type.ICE]: 2,
  },
  [Pokemon.Type.BUG]: {
    [Pokemon.Type.FIGHTING]: 0.5,
    [Pokemon.Type.FLYING]: 0.5,
    [Pokemon.Type.POISON]: 0.5,
    [Pokemon.Type.GHOST]: 0.5,
    [Pokemon.Type.STEEL]: 0.5,
    [Pokemon.Type.FIRE]: 0.5,
    [Pokemon.Type.GRASS]: 2,
    [Pokemon.Type.PSYCHIC]: 2,
    [Pokemon.Type.DARK]: 2,
    [Pokemon.Type.FAIRY]: 0.5,
  },
  [Pokemon.Type.GHOST]: {
    [Pokemon.Type.NORMAL]: 0,
    [Pokemon.Type.GHOST]: 2,
    [Pokemon.Type.PSYCHIC]: 2,
    [Pokemon.Type.DARK]: 0.5,
  },
  [Pokemon.Type.STEEL]: {
    [Pokemon.Type.ROCK]: 2,
    [Pokemon.Type.STEEL]: 0.5,
    [Pokemon.Type.FIRE]: 0.5,
    [Pokemon.Type.WATER]: 0.5,
    [Pokemon.Type.ELECTRIC]: 0.5,
    [Pokemon.Type.ICE]: 2,
    [Pokemon.Type.FAIRY]: 2,
  },
  [Pokemon.Type.FIRE]: {
    [Pokemon.Type.ROCK]: 0.5,
    [Pokemon.Type.BUG]: 2,
    [Pokemon.Type.STEEL]: 2,
    [Pokemon.Type.FIRE]: 0.5,
    [Pokemon.Type.WATER]: 0.5,
    [Pokemon.Type.GRASS]: 2,
    [Pokemon.Type.ICE]: 2,
    [Pokemon.Type.DRAGON]: 0.5,
  },
  [Pokemon.Type.WATER]: {
    [Pokemon.Type.GROUND]: 2,
    [Pokemon.Type.ROCK]: 2,
    [Pokemon.Type.FIRE]: 2,
    [Pokemon.Type.WATER]: 0.5,
    [Pokemon.Type.GRASS]: 0.5,
    [Pokemon.Type.DRAGON]: 0.5,
  },
  [Pokemon.Type.GRASS]: {
    [Pokemon.Type.FLYING]: 0.5,
    [Pokemon.Type.POISON]: 0.5,
    [Pokemon.Type.GROUND]: 2,
    [Pokemon.Type.ROCK]: 2,
    [Pokemon.Type.BUG]: 0.5,
    [Pokemon.Type.STEEL]: 0.5,
    [Pokemon.Type.FIRE]: 0.5,
    [Pokemon.Type.WATER]: 2,
    [Pokemon.Type.GRASS]: 0.5,
    [Pokemon.Type.DRAGON]: 0.5,
  },
  [Pokemon.Type.ELECTRIC]: {
    [Pokemon.Type.FLYING]: 2,
    [Pokemon.Type.GROUND]: 0,
    [Pokemon.Type.WATER]: 2,
    [Pokemon.Type.GRASS]: 0.5,
    [Pokemon.Type.ELECTRIC]: 0.5,
    [Pokemon.Type.DRAGON]: 0.5,
  },
  [Pokemon.Type.PSYCHIC]: {
    [Pokemon.Type.FIGHTING]: 2,
    [Pokemon.Type.POISON]: 2,
    [Pokemon.Type.STEEL]: 0.5,
    [Pokemon.Type.PSYCHIC]: 0.5,
    [Pokemon.Type.DARK]: 0,
  },
  [Pokemon.Type.ICE]: {
    [Pokemon.Type.FLYING]: 2,
    [Pokemon.Type.GROUND]: 2,
    [Pokemon.Type.STEEL]: 0.5,
    [Pokemon.Type.FIRE]: 0.5,
    [Pokemon.Type.WATER]: 0.5,
    [Pokemon.Type.GRASS]: 2,
    [Pokemon.Type.ICE]: 0.5,
    [Pokemon.Type.DRAGON]: 2,
  },
  [Pokemon.Type.DRAGON]: {
    [Pokemon.Type.STEEL]: 0.5,
    [Pokemon.Type.DRAGON]: 2,
    [Pokemon.Type.FAIRY]: 0,
  },
  [Pokemon.Type.DARK]: {
    [Pokemon.Type.FIGHTING]: 0.5,
    [Pokemon.Type.GHOST]: 2,
    [Pokemon.Type.PSYCHIC]: 2,
    [Pokemon.Type.DARK]: 0.5,
    [Pokemon.Type.FAIRY]: 0.5,
  },
  [Pokemon.Type.FAIRY]: {
    [Pokemon.Type.FIGHTING]: 2,
    [Pokemon.Type.POISON]: 0.5,
    [Pokemon.Type.STEEL]: 0.5,
    [Pokemon.Type.FIRE]: 0.5,
    [Pokemon.Type.DRAGON]: 2,
    [Pokemon.Type.DARK]: 2,
  },
};
